#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Workflows to notify the team about github issues

on:
  issues:
    types: [opened, reopened]
jobs:
  shared-vars:
    uses: ./.github/workflows/shared-vars.yml
  
  message:
    runs-on: ${{ needs.shared-vars.outputs.os }}
    needs: shared-vars
    steps:
    - uses: actions/checkout@v4
    - name: Send a stream message
      uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5
      env:
        CONTENT: "I have detected a new issue on ${{ github.event.repo.name }}.\nLink: ${{ github.event.issue.html_url }}\nThis is an automatically relayed message. Don't reply to me directly.\n-- Issue description:\n${{ github.event.issue.body }}"
      with:
        api-key: ${{ secrets.ZULIP_BOT_SECRET }}
        email: 'github-kogito-bot@kie.zulipchat.com'
        organization-url: 'https://kie.zulipchat.com'
        to: 'kogito'
        type: 'stream'
        topic: 'GitHub Issues - ${{ github.event.issue.title }}'
        content: ${{ env.CONTENT }}
