name: Kogito Runtimes Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

jobs:
  runtime-build:
    concurrency:
      group: kogito_runtimes_pr-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
        maven-version: ['3.8.6']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Maven Build
    steps:
      - name: Clean Disk Space
        uses: kiegroup/kie-ci/.ci/actions/ubuntu-disk-space@1.13.x
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: kiegroup/kie-ci/.ci/actions/long-paths@1.13.x
      - name: Java and Maven Setup
        uses: kiegroup/kie-ci/.ci/actions/maven@1.13.x
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: kiegroup/kie-ci/.ci/actions/build-chain@1.13.x
        env:
          BUILD_MVN_OPTS: '-Dproductized'
        with:
          definition-file: 'https://raw.githubusercontent.com/${GROUP:kiegroup}/kogito-pipelines/${BRANCH:main}/.ci/pull-request-config.yaml'
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Surefire Report
        uses: kiegroup/kie-ci/.ci/actions/surefire-report@1.13.x
        if: ${{ always() }}
        with:
          report_paths: '**/*-reports/TEST-*.xml'
