# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jenkins Tests

on:
  pull_request:
    paths: 
    - '.ci/jenkins/**'
    - '.github/workflows/jenkins-tests-PR.yml'

jobs:
  jenkinsfile-tests:
    concurrency:
      group: ${{ github.repository.name }}_jenkinsfile_tests-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: Jenkinsfiles
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: main

    - name: Checkout shared libraries
      uses: actions/checkout@v4
      with:
        repository: apache/incubator-kie-kogito-pipelines
        path: jenkins-pipeline-shared-libraries

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
        check-latest: true

    - name: Setup pipeline env
      run: cd $GITHUB_WORKSPACE/main/.ci/jenkins/tests && ./setup_pipeline_env.sh
      
    - name: Test pipelines
      run: cd $GITHUB_WORKSPACE/main/.ci/jenkins/tests && mvn -B clean test

  dsl-tests:
    concurrency:
      group: ${{ github.repository.name }}_dsl_tests-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: DSL
    steps:
    - name: DSL tests
      uses: apache/incubator-kie-kogito-pipelines/.ci/actions/dsl-tests@main
      with:
        main-config-file-repo: apache/incubator-kie-kogito-pipelines
        main-config-file-path: .ci/jenkins/config/main.yaml
        branch-config-file-repo: apache/incubator-kie-kogito-pipelines