name: Test analysis

on:
  workflow_run:
    workflows: [Kogito Runtimes Build]
    types:
      - completed

jobs:
  test-analysis:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    name: Test analysis
    steps:
      - uses: actions/checkout@v2
      - name: Download surefire reports
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "surefire-reports.zip"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/surefire-reports.zip`, Buffer.from(download.data));
      - name: Unzip files
        run: unzip surefire-reports.zip
      - name: Surefire Report
        uses: kiegroup/kogito-pipelines/.ci/actions/surefire-report@main
        if: ${{ always() }}
        with:
          check_name: ${{ github.event.workflow_run.name  }} test report
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: '**/surefire-reports/TEST-*.xml'
          skip_publishing: false
